#######################################################################################
####
#### User Guide on Configuration 
####
#######################################################################################

# Location of data file
file_path: './data/hdb_resale_price.csv'

## Training and Testing Dataset Configuration
# Specify the target column
target_column: resale_price

# Specify the percentage of data reserve for testing
val_test_size: 0.4

# Specify the percentage of data reserve for validation
val_size: 0.5

## Features Classification
numerical_features:
  - floor_area_sqm
  - remaining_lease_by_months
  - transac_year
nominal_features:
  - transac_month
  - town
  - flat_model
  - flat_type
passthrough_features:
  - storey_range
